# -*- coding: utf-8 -*-
"""summarizer_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nfs_C7CE1KWpNGOiyK4jQGa-EXD9m8ge

Om Muruga
"""

import os

# Setting up API keys
#os.environ["OPENAI_API_KEY"] = "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"

import streamlit as st
from langchain.document_loaders import YoutubeLoader
from langchain.llms import OpenAI
from langchain.chains.summarize import load_summarize_chain
from langchain.text_splitter import RecursiveCharacterTextSplitter

# LLM chain

def load_youtube_video(youtube_video):
    loader = YoutubeLoader.from_youtube_url(youtube_video, add_video_info=True)
    transcripts = loader.load()
    return transcripts

# Page Configuration

st.set_page_config(page_title="YouTube Summarizer",
                            page_icon="🖥️",
                            layout="centered",
                            initial_sidebar_state="expanded",
                            )

# Header

st.header("YouTube Summarizer")

# Columns

col1, col2 = st.columns(2, gap="small")
youtube_video=""
api_key=""
with col1:
    st.markdown("""Uses LangChain to pass transcripts from Youtube videos
                            to OpenAI LLMs and summarises them. \n\n*Powered by OpenAI gpt4*"""
                        )

with col2:
    youtube_url = "https://www.youtube.com/watch?v=u5e2CSRXKuE"
    youtube_video = st.text_input(label="Youtube URL", placeholder="Enter youtube url...")
    if youtube_video:
        st.video(youtube_video)
        api_key = st.text_input(label="OpenAI API Key ",  placeholder="Ex: sk-2twmA8t...", key="openai_api_key_input")
        if not api_key:
            st.warning('Please insert OpenAI API Key. Instructions [here](https://help.openai.com/en/articles/4936850-where-do-i-find-my-secret-api-key)', icon="⚠️")
            st.stop()
        llm = OpenAI(temperature=0, openai_api_key=api_key)
        chain = load_summarize_chain(llm, chain_type="stuff", verbose=False)

with col1:
    if len(youtube_video) > 0:
        with st.spinner(text='Please Wait...'):
            transcripts = load_youtube_video(youtube_video)
            summary = chain.run(transcripts)
            st.markdown("**Summary of the video content**")
            st.write(summary)